blogging/urls.py
from django.urls import path
from blogging.views import BlogListView, BlogDetailView, add_post

urlpatterns = [
    path("add/", add_post, name="add_post"),
    path("posts/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("", BlogListView.as_view(), name="blog_index"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.shortcuts import render
from .forms import SignUpForm
from django.contrib.auth import authenticate, login
from django.contrib import messages


def logout_view(request):
    logout(request)
    return redirect('/login')


def signup_view(request):
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/login')
		else:
			messages.error(request, 'Correct the errors below')
	else:
		form = SignUpForm()

	return render(request, 'signup.html', {'form': form})


urlpatterns = [
    path("", include("blogging.urls")),
    path("polling/", include("polling.urls")),
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    # path("logout/", LogoutView.as_view(next_page='/login'), name="logout"),   # doesn't work
    path("logout/", logout_view, name="logout"),
    path('signup/', signup_view, name='sign_up'),
    # path("", include("django.contrib.auth.urls")),
    # path("accounts/", include("accounts.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
]

polling/urls.py
from django.urls import path
from polling.views import PollListView, PollDetailView

urlpatterns = [
    path("", PollListView.as_view(), name="poll_index"),
    path("polls/<int:pk>/", PollDetailView.as_view(), name="poll_detail"),
]

blogging/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name="categories")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class CategoryInline(admin.TabularInline):
    model = Category.posts.through


class PostAdmin(admin.ModelAdmin):
    list_display = ("title", "author", "created_date", "published_date")
    list_filter = ("published_date", "author")
    search_fields = ("title", "text")
    inlines = [CategoryInline]


class CategoryAdmin(admin.ModelAdmin):
    list_display = ("name", "description")
    search_fields = ("name", "description")
    exclude = ("posts",)

polling/models.py
from django.db import models


class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

blogging/forms.py
from django import forms
from .models import Post
from django.utils.timezone import now


class PostForm(forms.ModelForm):
    publish_now = forms.BooleanField(
        required=False,
        label="Publish",
        help_text="Check this box to publish the post immediately."
    )

    class Meta:
        model = Post
        fields = ['title', 'text', 'publish_now']  # Add publish_now, exclude published_date

    def save(self, commit=True):
        instance = super().save(commit=False)

        if self.cleaned_data.get('publish_now'):
            instance.published_date = now()
        else:
            instance.published_date = None

        if commit:
            instance.save()
        return instance

mysite/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	email = forms.EmailField()
	
	class Meta:
		model = User
		fields = ["username", "email", "password1", "password2"]

blogging/views.py
from django.shortcuts import render
from blogging.models import Post
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .forms import PostForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


class BlogListView(LoginRequiredMixin, ListView):
    queryset = Post.objects.exclude(published_date__exact=None).order_by(
        "-published_date"
    )
    template_name = "blogging/list.html"


class BlogDetailView(LoginRequiredMixin, DetailView):
    queryset = Post.objects.exclude(published_date__exact=None)
    template_name = "blogging/detail.html"


@login_required
def add_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('/')
    else:
        form = PostForm()
    return render(request, 'blogging/add.html', {'form': form})

polling/views.py
from django.shortcuts import render
from polling.models import Poll
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin


class PollListView(LoginRequiredMixin, ListView):
    model = Poll
    template_name = "polling/list.html"


class PollDetailView(LoginRequiredMixin, DetailView):
    model = Poll
    template_name = "polling/detail.html"

    def post(self, request, *args, **kwargs):
        poll = self.get_object()

        if request.POST.get("vote") == "Yes":
            poll.score += 1
        else:
            poll.score -= 1
        poll.save()

        context = {"object": poll}
        return render(request, "polling/detail.html", context)

blogging/templates/blogging/add.html
{% extends "base.html" %}

{% block content %}
<h1>Create a New Post</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

blogging/templates/blogging/detail.html
{% extends "base.html" %}

{% block content %}
<a class="backlink" href="/">Home</a>
<h1>{{ post }}</h1>
<p class="byline">
  Posted by {{ object.author.username }} &mdash; {{ object.published_date }}
</p>
<div class="post-body">
  {{ object.text }}
</div>
<ul class="categories">
  {% for category in object.categories.all %}
    <li>{{ category }}</li>
  {% endfor %}
</ul>
{% endblock %}

blogging/templates/blogging/list.html
{% extends "base.html" %}{% block content %}
  <h1>Coolest Posts</h1>
  {% comment %} here is where the query happens {% endcomment %}
  {% for post in post_list %}
  <div class="post">
    <h2><a href="{% url 'blog_detail' post.pk %}">{{ post }}</a></h2>
    <p class="byline">
      Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
    </p>
    <div class="post-body">
      {{ post.text }}
    </div>
    <ul class="categories">
      {% for category in post.categories.all %}
        <li>{{ category }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endfor %}
{% endblock %}

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>My Django Blog</title>
    <link type="text/css" rel="stylesheet" href="{% static 'django_blog.css' %}">
  </head>
  <body>
    <div id="header">  {# header begins here #}
      <ul id="control-bar">
      {% if user.is_authenticated %}
       {% if user.is_staff %}<li><a href="{% url 'admin:index' %}">Admin</a></li>{% endif %}
        <li><a href="{% url 'blog_index' %}">Post</a></li>
        <li><a href="{% url 'add_post' %}">Add Post</a></li>
        <li><a href="{% url 'poll_index' %}">Polls</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
       {% else %}
        <li><a href="{% url 'sign_up' %}">Sign Up</a></li>
        <li><a href="{% url 'login' %}">Login</a></li>
      {% endif %}
      </ul>
    </div>
    <div id="container">
      <div id="content">
      {% block content %}
       [content will go here]
      {% endblock %}
      </div>
    </div>
  </body>
</html>

mysite/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>
<form action="" method="POST">{% csrf_token %}
  {{ form.as_p }}
  <p><input type="submit" value="Log In"></p>
</form>
{% endblock %}

mysite/templates/signup.html
{% extends "base.html" %}

{% block content %}
<h1>Sign Up</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit">Sign Up</button>
</form>
{% endblock %}

polling/templates/polling/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ object.title }}</h1>
<div class="poll-body">
    {{ object.text }}
</div>
<div class="poll-score">
    Current score: {{ object.score }}
</div>
<div class="poll-vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock %}

polling/templates/polling/list.html
{% extends "base.html" %}
{% block content %}
<h1>Polls</h1>
{% for poll in poll_list %}
    <div class="poll">
        <h2>
            <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock %}